spring:
  application:
    name: equipment-rental-api
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.xml
    default-schema: rental_equipment
    driver-class-name: org.h2.Driver
    user: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:rental_equipment;INIT=CREATE SCHEMA IF NOT EXISTS rental_equipment;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  cache:
    type: HAZELCAST
    cache-names:
      - products
      - prices
      - productInfo

server:
  port: 8088
  tomcat:
    threads:
      max: 2
  max-http-header-size:
    48KB
  servlet:
    context-path: /rental/api/v1

api:
  cache:
    time-to-live:
      -
        name: products
        seconds: 1800
      -
        name: prices
        seconds: 1800
      -
        name: productInfo
        seconds: 1800
  swagger:
    version: 0.0.1
    title: Equipment Rental API
    description: Gaming equipment rental price calculation API
    contact-name: Edvardas Jusius
    url: https://github.com/Dum6o
    contact: e2businesslt@gmail.com
  security:
    username: admin
    password: admin
    roles:
      - ADMIN
      - USER
    path-whitelist:
      - /actuator/**
      - /v2/api-docs
      - /swagger-resources
      - /swagger-resources/**"
      - /configuration/ui
      - /configuration/security
      - /swagger-ui.html
      - /webjars/**
      - /v3/api-docs/**
      - /swagger-ui/**
      - /h2-console/**